##########################
f1 = "water.xyz"
f2 = "data.waternew"
f3 = "cu_fcc.xyz"

m1 = 63.546001 # Cu
m2 = 1.007940 # H
m3 = 15.999400 # O

##########################
max_x = -float("inf")
max_y = -float("inf")
max_z = -float("inf")
min_x = float("inf")
min_y = float("inf")
min_z = float("inf")

num_atoms = 0 
file1 = open(f1, "r")

i = 0
for line in file1:
    if(i > 2):
        if(float(line.split()[1]) < min_x):
            min_x = float(line.split()[1])
        if(float(line.split()[2]) < min_y):
            min_y = float(line.split()[2])
        if(float(line.split()[3]) < min_z):
            min_z = float(line.split()[3])
        if(float(line.split()[1]) > max_x):
            max_x = float(line.split()[1])
        if(float(line.split()[2]) > max_y):
            max_y = float(line.split()[2])
        if(float(line.split()[3]) > max_z):
            max_z = float(line.split()[3])
    i = i + 1
R =  ((min_x+min_y+min_z)/3 - (max_x+max_y+max_z)/3)/2


print("x ", min_x, " ", max_x)
print("y ", min_y, " ", max_y)
print("z ", min_z, " ", max_z)
#################################################
max_x1 = -float("inf")
max_y1= -float("inf")
max_z1 = -float("inf")
min_x1 = float("inf")
min_y1 = float("inf")
min_z1 = float("inf")

file3 = open(f3, "r")
i = 0
for line in file3:
    if(i > 2):
        num_atoms = num_atoms + 1
        if(float(line.split()[1]) < min_x1):
            min_x1 = float(line.split()[1])
        if(float(line.split()[2]) < min_y1):
            min_y1 = float(line.split()[2])
        if(float(line.split()[3]) < min_z1):
            min_z1 = float(line.split()[3])
        if(float(line.split()[1]) > max_x1):
            max_x1 = float(line.split()[1])
        if(float(line.split()[2]) > max_y1):
            max_y1 = float(line.split()[2])
        if(float(line.split()[3]) > max_z1):
            max_z1 = float(line.split()[3])
    i = i + 1

D = 3 
d = abs(R) + (max_z1 - min_z1) + D
file3.close()
avg_x1 = (max_x1 - min_x1)/2
avg_y1 = (max_y1 - min_y1)/2
avg_z1 = (max_z1 - min_z1)/2

print("x ", min_x1 , " ", max_x1)
print("y ", min_y1, " ", max_y1)
print("z ", min_z1, " ", max_z1)
##############################################
extend = abs(R)*2
###############################################
molecules = []

i = 0
num_water_atoms = 0

file1 = open(f1, "r")
f = open('roundwater.xyz','w')

for line in file1:
        if (len(line.split()) == 4):
            molecules.append([line.split()[0], float(line.split()[1]), float(line.split()[2]), float(line.split()[3])])
            i = i + 1
            if(i == 3):
                i = 0
                can = [False,False,False]
                j = 0
                for water in molecules:
                    x = float(water[1]) 
                    y = float(water[2]) 
                    z = float(water[3])
                    if(z**2 <= (R**2 - (y)**2 - (x)**2)):
                        can[j] = True
                    else:
                        can[j] = False
                    j = j + 1
                if(False not in can):
                    f.write(molecules[0][0]+"        "+ str(float(molecules[0][1]))+"       "+str(float(molecules[0][2]))+"       "+str(float(molecules[0][3]+d)))
                    f.write("\n")
                    f.write(molecules[1][0]+"        "+ str(float(molecules[1][1]))+"       "+str(float(molecules[1][2]))+"       "+str(float(molecules[1][3]+d)))
                    f.write("\n")
                    f.write(molecules[2][0]+"        "+ str(float(molecules[2][1]))+"       "+str(float(molecules[2][2]))+"       "+str(float(molecules[2][3]+d)))
                    f.write("\n")
                    num_water_atoms = num_water_atoms + 3
                    num_atoms = num_atoms + 3
                molecules = []
                
f.close()
file1.close()
######################################################
with open(f2,'w') as file2:
    file2.write("LAMMPS data file. CGCMM style. atom_style full generated by VMD/TopoTools v1.2 on Fri Apr 26 18:31:16 +08 2019")
    file2.write("\n")
    file2.write(" " + str(num_atoms) + " " + "atoms")
    file2.write("\n")
    file2.write(" " + str(3) + " " + "atom types")
    file2.write("\n")
    file2.write(" " + str(int(num_water_atoms/3)) + " " + "angles")
    file2.write("\n")
    file2.write(" " + str(int(num_water_atoms/3*2)) + " " + "bonds")
    file2.write("\n")
    file2.write(" " + str(1) + " " + "bond types")
    file2.write("\n")
    file2.write(" " + str(1) + " " + "angle types")
    file2.write("\n")
    file2.write("\n")
    file2.write(" " + str(min_x1-(min_x1+avg_x1)-extend) + " " + str(max_x1-(min_x1+avg_x1)+extend) + " xlo xhi")
    file2.write("\n")
    file2.write(" " + str(min_y1-(min_y1+avg_y1)-extend) + " " + str(max_y1-(min_y1+avg_y1)+extend) + " ylo yhi")
    file2.write("\n")
    file2.write(" " + str(-extend) + " " + str(max_z1-min_z1+abs(R)+abs(R)+extend) + " zlo zhi")
    file2.write("\n")
    file2.write("\n")
    file2.write(" Masses")
    file2.write("\n")
    file2.write("\n")
    file2.write(" " + "1 " + str(m1) + " #Cu")
    file2.write("\n")
    file2.write(" " + "2 " + str(m2) + " #H")
    file2.write("\n")
    file2.write(" " + "3 " + str(m3) + " #O")
    file2.write("\n")
    file2.write("\n")
    file2.write(" " + "Atoms")
    file2.write("\n")
    file2.write("\n")

    
    c = 1
    s = 0
    file1 = open('roundwater.xyz', "r")
    for line in file1:
        if((c-1)%3 == 0):
            s = s + 1
            
        if(line.split()[0] == "O"):
            file2.write(str(c)+" "+str(s)+" "+str(3)+" 0.00000 "+line.split()[1]+" "+line.split()[2]+" "+line.split()[3]+" # O")
            file2.write("\n")
        else:
            file2.write(str(c)+" "+str(s)+" "+str(2)+" 0.00000 "+line.split()[1]+" "+line.split()[2]+" "+line.split()[3]+" # H")
            file2.write("\n")
        
        c = c + 1
    file3 = open(f3, "r")
    i = 0
    for line in file3:
        if(i > 2):
            x = str(float(line.split()[1]) - (min_x1+avg_x1))
            y = str(float(line.split()[2]) - (min_y1+avg_y1))
            z = str(float(line.split()[3]) - (min_z1))
            file2.write(str(c)+" "+str(s)+" "+str(1)+" 0.00000 "+x+" "+y+" "+z+" # Cu")
            file2.write("\n")
            c = c + 1
        i = i + 1
        s = s + 1
    
        

    file1.close()
    file3.close()


    num_bonds = int(2*(num_water_atoms/3))
    num_angles = int(num_water_atoms/3)

    file2.write("\n")
    file2.write(" Bonds")
    file2.write("\n")
    file2.write("\n")
    u = 1
    for i in range(1,int(num_bonds+1),2):
        file2.write(str(i)+"       "+"1"+"    "+str(u)+"    "+str(u+1)+" #  O: H")
        file2.write("\n")
        file2.write(str(i+1)+"       "+"1"+"    "+str(u)+"    "+str(u+2)+" #  O: H")
        file2.write("\n")
        u = u + 3

    file2.write("\n")
    file2.write("\n")
    file2.write(" Angles")
    file2.write("\n")
    file2.write("\n")
    u=1
    for i in range(1,int(num_angles)+1):
        file2.write(str(i)+"       "+str(1)+"    "+str(i*3)+"    "+str(u)+"    "+str(u+1)+" #  H: O: H")
        file2.write("\n")
        u = u + 3
        
    file2.close()


